### PR TITLE
Update rules + README to track 2.10.2

### PR DESCRIPTION
**Pull request by baer**
The big change is is correcting the README to properly document the tracked version of ESLint

@ryan-roemer

### CODE REVIEW

**Comment by dylancwood** [comment]
@ryan-roemer do you know why the travis-ci tests didn't run for this PR?

**Comment by ryan-roemer** [comment]
@baer @dylancwood -- Looking...

**Comment by ryan-roemer** [comment]
Weird... https://travis-ci.org/walmartlabs/eslint-config-walmart/pull_requests

Travis _is_ set up for this repo...

Searching on travis status, might be this related GitHub Issue? https://twitter.com/traviscistatus/status/734804357326069760

If that's resolved now, closing and re-opening might kickstart the travis hook, so I'm going to try that next.

**Comment by ryan-roemer** [comment]
Closing to kick travis. Will reopen next.

**Comment by ryan-roemer** [comment]
And back open we go...

**Comment by dylancwood** [comment]
:+1:

**Pull request merged**
