### PR TITLE
[PATCH] 📝  JavaScript style guide

### PR DESCRIPTION
**Pull request by markbrouch**
### Summary

This PR adds a JavaScript and React style guide, covering all eslint rules for ES5, ES6, and React, plus select other code style best practices.
### Reviewers

@baer @chaseadamsio @ryan-roemer

### CODE REVIEW

**Comment by baer** [comment]
How was this generated?

**Comment by markbrouch** [comment]
@baer manually

**Comment by baer** [comment]
Wow! Thanks for such a through job on this. Is there a way to generate anything here? It seems hard to keep up to date.

**Comment by markbrouch** [comment]
@baer I definitely gave automation thought, but ultimately not everything represented in this style guide comes from an eslint rule, and the examples are all custom made to best illustrate the rule. I think the best way to keep it updated would be to require any PR to a rule also include appropriate documentation updates.

**Comment by ryan-roemer** [comment]
@markbrouch -- High level guide LGTM...

**Comment by dstevensio** [comment]
After a couple of readthroughs, I think this looks good. Nice work, a lot of effort went in here.

LGTM

**Pull request merged**
